### ISSUE TITLE
ABLLinkRequestBeatAtTime() sometimes mapping to a beat time in the past?

### ISSUE THREAD

**Issue by lijon** [Ableton/link#135]
I call `ABLLinkRequestBeatAtTime()` with for example beatTime 0. I then do `gotBeat = ABLLinkBeatAtTime()` to see what the actual beat time is for the given host time. With peers connected, `gotBeat` is (and should) always be something less than beatTime, but aligned with the phase. However, when no peers are connected, this is assumed to be the same value as `beatTime` but in this case I sometimes get a plus or minus 1e-06 diff.

This assumption broke some things in my app, because if I request beat 0 and it actually starts on beat 0.000001, it means any events scheduled on beat 0.000000 are missed.

A simple fix that seems to work is to just clip `gotBeat` so it can't be greater than the requested beat time mapping for the given host time:

```c
ABLLinkRequestBeatAtTime(sessionState, currentBeat, hostTime, quantum);
double gotBeat = ABLLinkBeatAtTime(sessionState, hostTime, quantum);
if(gotBeat <= currentBeat) { // we *should* only get a beat time earlier or equal to the requested time, clip otherwise
    currentBeat = gotBeat;
}
```

**Comment by lijon** [comment]
This is on iOS/iPadOS. I haven't noticed the issue before, but it only happens at some tempo ranges (for example 31 to 49 bpm) so it could be that I simply haven't triggered it before. I did update to latest ABLLink SDK but that didn't help.

**Comment by fgo-ableton** [comment]
Here's a [LinkKit](https://github.com/Ableton/link/files/12474521/LinkKit.zip) build that should address the issue. Could you give it a try?

**Comment by fgo-ableton** [comment]
Internally we are representing the beat values with ints. So the issue you are seeing is really, that the exact beat time you are requesting can not be represented accurately.
What we are doing to address this is to make sure, that the quantized beat time after calling `requestBeatAtTime()` is never earlier than the float value coming in. When we see this happen we shift the timeline slightly.
We can not clip the value as you did, because when `beatAtTime()` is called we don't really know the arguments that were passed to `requestBeatAtTime()` earlier.
I am not super happy with that solution, but I guess it will do. I'll try to make a new release next week or so.

**Comment by lijon** [comment]
So would it be better that I manually clip the value (since I know which beat time I requested) instead?

**Comment by fgo-ableton** [comment]
We just released a [new version of LinkKit](https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.2.0) that contains a fix for the issue.
