### ISSUE TITLE
Readme:  std::chrono::high_resolution_clock ?

### ISSUE THREAD

**Issue by JoergAtGithub** [Ableton/link#136]
The Readme states `C++ standard library std::chrono::high_resolution_clock-based implementation in [platforms/stl/Clock.hpp](https://github.com/Ableton/link/blob/master/include/ableton/platforms/stl/Clock.hpp)`

I wonder if std::chrono::high_resolution_clock is really used there, I see only `steady_clock` in the code, but not `high_resolution_clock`

**Comment by cdi-ableton** [comment]
Indeed, `std::chrono::high_resolution_clock` is not used anymore. We switched to `std::chrono::steady_clock` since `high_resolution_clock` is not guaranteed to be monotonic (see https://github.com/Ableton/link/commit/a40326dcc253529db756f401ba9043feee1adabc). Unfortunately, we didn't update the documentation accordingly. So thanks for the heads-up, we'll update the `README.md`.

**Comment by JoergAtGithub** [comment]
Thanks for updating README.md!
