### ISSUE TITLE
forceBeatAtTime notification

### ISSUE THREAD

**Issue by samkuhn** [Ableton/link#63]
Hi Guys, We're currently trying to integrate with the cpp library and have a legitimate need for forceBeatAtTime (we are purely controlling visuals through link and sometimes a re-sync is necessary to keep in time with external music).

What I don't understand is how to use the API to listen for forceBeatAtTime called by other hosts.

Neither the tempo or stop/start callbacks seem to fire in this case.. How does an app get notified that a forceBeatAtTime has occurred from another host in the session?

Thanks, 

Sam

**Comment by samkuhn** [comment]
Sorry my mistake I realised I'm just looking for phase changes and can just poll phase at time and calculate using the last value received from the tempo callback.

**Comment by fgo-ableton** [comment]
Hey Sam,

Great you figured it out!
 
In general you should not use the tempo provided in the tempo callback to calculate the phase of the visuals you are rendering. This tempo value is just meant to be shown to the user, as the common tempo of all peers.
Effectively the peers might have to run a little slower or faster than this, due to the clock drift of the different computers. To accommodate for this you should solely use information provided by the SessionState. ie. phaseAtTime or beatAtTime to steer your rendering process.

Hope that helps, Florian
